-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgaVC8zlco+LKwCT9W
xYZQE3Fq/E9uKx1biTzxqVZG/EOgCgYIKoZIzj0DAQehRANCAAQ0t3V1T9qfabZ8
E3Kfijsjd7YgRVDMMvvQiglShvXxNxB0nJOkJKvGnOtxP9g6BTD69IVniboxCdqz
gKyvfZoS
-----END PRIVATE KEY-----